version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - pip install instructlab huggingface_hub
  build:
    commands:
      - echo "Hello World"

artifacts:
  files:
    - '**/*'
