version: 0.2
env:
  variables:
    CUDA_HOME: "/usr/local/cuda"
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - apt-get update && apt-get install -y cmake
  pre_build:
    commands:
      - echo "Installing CUDA Toolkit"
      - echo "Ubuntu version:"
      - lsb_release -a
      - apt-get update
      - apt-get install -y cuda-drivers
      - wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
      - dpkg -i cuda-keyring_1.0-1_all.deb
      - apt-get update
      - apt-get install -y cuda-toolkit-11-8
      - export PATH=/usr/local/cuda-11.8/bin${PATH:+:${PATH}}
      - export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
      - nvcc --version
      - nvidia-smi
  build:
    commands:
      - echo "Installing Python dependencies"
      - pip install --upgrade pip

      - echo "Installing PyTorch"
      - pip uninstall -y torch
      - pip cache purge
      - pip install torch --index-url https://download.pytorch.org/whl/cu118

      - echo "Installing llama-cpp-python"
      - pip uninstall -y llama-cpp-python
      - pip cache remove llama_cpp_python
      - CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.75 --no-cache-dir

      - echo "Installing InstructLab"
      - pip install instructlab --no-cache-dir
      - echo "Cloning repositories"
      - git clone https://github.com/nicklamb97/generated.git
      - git clone https://github.com/nicklamb97/instructlab-config.git

      - echo "Copying config file"
      - cp instructlab-config/config.yaml .
      - ilab --help

      - echo "Installing huggingface_hub"
      - pip install huggingface_hub

      - echo "Downloading pre-trained model"
      - ilab model download --repository=NickLamb/OpenROAD-7B-Instruct --filename=OpenROAD-7B-Instruct.Q4_K_M.gguf

      - echo "Uploading to Hugging Face"
      - |
        python -c "
        from huggingface_hub import login, upload_folder
        login(token='${HF_TOKEN}')
        upload_folder(
            folder_path='models',
            path_in_repo='',
            repo_id='NickLamb/OpenROAD-7B-Instruct',
            repo_type='model'
        )
        "
artifacts:
  files:
    - '**/*'
